parlay_history = '''
{
  "Week 10 2024": [
    {
      "owner": "James",
      "date": "2024-11-10",
      "total_odds": "+0",
      "bets": [
        {
          "bet": "Anytime TD Scorer - WR Cooper Kupp @ LA Rams",
          "result": "PENDING",
          "owner": "James"
        },
        {
          "bet": "Derek Carr over passing yards",
          "result": "WIN",
          "owner": "Jeff"
        },
        {
          "bet": "49ers -6.5",
          "result": "PENDING",
          "owner": "Jon"
        },
        {
          "bet": "Steelers moneyline",
          "result": "PENDING",
          "owner": "Sam/Connor"
        }
      ],
      "parlay_result": "PENDING"
    }
  ],
  "Week 9 2024": [
    {
      "owner": "James",
      "date": "2024-11-10",
      "total_odds": "+0",
      "bets": [
        {
          "bet": "Over 1.5 - Justin Tucker FGs @ Baltimore Ravens",
          "result": "WIN",
          "owner": "James"
        },
        {
          "bet": "New England patriots moneyline",
          "result": "PENDING",
          "owner": "Jeff"
        },
        {
          "bet": "Saints moneyline",
          "result": "PENDING",
          "owner": "Jon"
        },
        {
          "bet": "Marvin Harrison anytime TD",
          "result": "PENDING",
          "owner": "Sam/Connor"
        }
      ],
      "parlay_result": "PENDING"
    }
  ],
  "Week 8 2024": [
    {
      "owner": "James",
      "date": "2024-11-10",
      "total_odds": "+0",
      "bets": [
        {
          "bet": "Anytime TD Scorer - WR Kalif Raymond @ Detroit Lions",
          "result": "WIN",
          "owner": "James"
        },
        {
          "bet": "Any time touchdown scorer - nick chubb",
          "result": "LOSS",
          "owner": "Jon"
        },
        {
          "bet": "Davante adams  jets @ ne patriots",
          "result": "LOSS",
          "owner": "Jeff"
        },
        {
          "bet": "Gibbs anytime ",
          "result": "WIN",
          "owner": "Dillon"
        },
        {
          "bet": "Ravens browns over 44.5",
          "result": "PENDING",
          "owner": "Sam/Connor"
        }
      ],
      "parlay_result": "PENDING"
    }
  ],
  "Week 11 2024": [
    {
      "owner": "Sam/Connor",
      "date": "2024-11-10",
      "total_odds": "+0",
      "bets": [
        {
          "bet": "Bengals Moneyline",
          "result": "PENDING",
          "owner": "Sam/Connor"
        }
      ],
      "parlay_result": "PENDING"
    }
  ]
}
'''

settings = '''
{
  "owners": [
    "James",
    "Jon",
    "Matt",
    "Pat",
    "Jack",
    "Jeff",
    "Sam/Connor",
    "Enzo",
    "Dillon",
    "Cole",
    "TBD"
  ],
  "parlay_fee": 20,
  "parlay_president": "James Quaglia"
}
'''